---
jenkins_user: "{{ lookup('env', 'JENKINS_USER') }}"
jenkins_password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
jenkins_jobs_builder_dir: "{{ lookup('env', 'JENKINS_JOBS_DIR')|default('/etc/jenkins_jobs', true) }}"
jenkins_jobs_dir: "{{ jenkins_jobs_builder_dir}}/jobs"
jenkins_jobs_conf: "{{ jenkins_jobs_builder_dir }}/jenkins_jobs.ini"
nginx_sites_available_dir: "/etc/nginx/sites-available"
nginx_sites_enabled_dir: "/etc/nginx/sites-enabled"
admin_dir: "/home/{{ ansible_user }}"
jenkins_cert_path: "{{ lookup('env', 'JENKINS_CERT_PATH')|default('/etc/letsencrypt/live/jenkins.romeyinc.net/fullchain.pem', true) }}"
jenkins_key_path: "{{ lookup('env', 'JENKINS_KEY_PATH')|default('/etc/letsencrypt/live/jenkins.romeyinc.net/privkey.pem', true) }}"
jenkins_port: 8080
jenkins_domain: "{{ lookup('env', 'JENKINS_DOMAIN')|default('jenkins.romeyinc.net', true) }}"
