- job:
    builders:
      - shell: curl https://cronitor.link/QTBpUX/run -m 10 ; /home/admin/edi/items.sh && curl https://cronitor.link/QTBpUX/complete -m 10
    description: 'Sumbit items for EDI'
    name: 'Item Submittal for EDI'
    disabled: true
    triggers:
      - timed: 0 8,9,10,11,12,13,14,15,16,17 * * 1,2,3,4,5
- job:
    builders:
      - shell: curl https://cronitor.link/2o6CEp/run -m 10 ; /home/admin/edi/salesorders.sh && curl https://cronitor.link/2o6CEp/complete -m 10
    description: 'Submit orders for EDI'
    name: 'Hourly Order submittal for EDI'
    disabled: true
    triggers:
      - timed: 0,30 8,9,10,11,13,14,15,16,17 * * 1,2,3,4,5
- job:
    builders:
      - shell: curl https://cronitor.link/nNlphr/run -m 10 ; /home/admin/edi/salesorders.sh && curl https://cronitor.link/nNlphr/complete -m 10
    description: 'Submit orders for EDI'
    name: 'Daily Order submittal for EDI'
    disabled: true
    triggers:
      - timed: 7 12 * * 1,2,3,4,5
- job:
    builders:
      - shell: curl https://cronitor.link/82DIuX/run -m 10 ; /home/admin/edi/shipconfirmation.sh && curl https://cronitor.link/82DIuX/complete -m 10
    description: 'Create invoices for EDI'
    name: 'Invoice creation for EDI'
    disabled: true
    triggers:
      - timed: '*/5 12,13,14,15,16,17,18,19,20,21,22 * * 1-5'
- job:
    builders:
      - shell: curl https://cronitor.link/BuQpff/run -m 10 ; /home/admin/edi/VerifyItems/verify-items.sh && curl https://cronitor.link/BuQpff/complete -m 10
    description: 'Backup EDI'
    name: 'EDI Daily Backup'
    disabled: true
    triggers:
      - timed: 0 2 * * *
- job:
    builders:
      - shell: curl https://cronitor.link/y7uG07/run -m 10 ; /home/admin/scripts/pg_backup_daily.sh && curl https://cronitor.link/y7uG07/complete -m 10
    description: 'Backup postgres'
    name: 'Postgres Daily backup'
    disabled: true
    triggers:
      - timed: 0 2 * * *
- job:
    builders:
      - shell: curl https://cronitor.link/mF2IHA/run -m 10 ;  /home/admin/scripts/pg_backup_hourly.sh && curl https://cronitor.link/mF2IHA/complete -m 10
    description: 'Backup Postgres'
    name: 'Postgres Hourly Backup'
    disabled: true
    triggers:
      - timed: 0 8,9,10,11,12,13,14,15,16,17,18,19,20,21 * * *
- job:
    builders:
      - shell: curl https://cronitor.link/0qeIvb/run -m 10 ;  /home/admin/scripts/hourly-sql.sh && curl https://cronitor.link/0qeIvb/complete -m 10
    description: 'Backup Postgres'
    name: 'Postgres SQL Hourly Backup'
    disabled: true
    triggers:
      - timed: 0 * * * *
- job:
    builders:
      - shell: curl https://cronitor.link/UyVpdN/run -m 10 ; /home/admin/scripts/pg_backup_monthly.sh && curl https://cronitor.link/UyVpdN/complete -m 10
    description: 'Backup postgres'
    name: 'Postgres Monthly Backup'
    disabled: true
    triggers:
      - timed: 0 0 1 * *
- job:
    builders:
      - shell: certbot renew
    description: 'Renew LetsEncrypt certificate'
    name: 'LetsEncrypt Certificate Renewal'
    disabled: true
    triggers:
      - timed: 30 2 * * 1
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh DailySalesMngmt
    description: 'Sales Management Report'
    name: 'Email Sales Management Report Daily'
    disabled: true
    triggers:
      - timed: 5 7 * * 1,2,3,4,5,6
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh OrdersSubmitted
    description: 'Submitted Orders Report'
    name: 'Email Submitted Orders Report Daily'
    disabled: true
    triggers:
      - timed: 8 12 * * 1,2,3,4,5
- job:
    builders:
      - shell: /home/admin/add-fotos/confirm-images.sh
    description: 'Confirm Images'
    name: 'Confirm Images Daily'
    disabled: true
    triggers:
      - timed: 7 7 * * 1,2,3,4,5
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh DailyDSI
    description: 'DSI Report'
    name: 'Email DSI Report Daily'
    disabled: true
    triggers:
      - timed: 5 7 * * 1,2,3,4,5
- job:
    builders:
      - shell: curl https://cronitor.link/pv7Iwt/run -m 10 ; /home/admin/romey-dw/update-sales.sh && curl https://cronitor.link/pv7Iwt/complete -m 10
    description: 'Update Datawarehouse Sales data'
    name: 'DataWarehouse Sales Data Update'
    disabled: true
    triggers:
      - timed: 5 4 * * 1,2,3,4,5,6
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh DSI
    description: 'DSI Report'
    name: 'Email DSI Report Weekly'
    disabled: true
    triggers:
      - timed: 5 7 * * 1
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh CustNoPurch
    description: 'Customer NoPurch Report'
    name: 'Email Customer NoPurch Report Weekly'
    disabled: true
    triggers:
      - timed: 7 7 * * 5
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh Preorders
    description: 'Preorders Report'
    name: 'Email Preorders Report Weekly'
    disabled: true
    triggers:
      - timed: 17 7 * * 5
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh SalesMetrics
    description: 'Sales Metrics Report'
    name: 'Email Sales Metrics Report Weekly'
    disabled: true
    triggers:
      - timed: 7 0 * * 1
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh SalesProdCatDetail
    description: 'SalesProdCatDetail Report'
    name: 'Email SalesProdCatDetail Report Weekly'
    disabled: true
    triggers:
      - timed: 7 7 * * 1
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh WeeklySalesMngmt
    description: 'Weekly Sales Management Report'
    name: 'Email Sales Management Report Weekly'
    disabled: true
    triggers:
      - timed: 5 7 * * 1
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh CustList
    description: 'Customer List Report'
    name: 'Email Customer List Report Monthly'
    disabled: true
    triggers:
      - timed: 5 7 1 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh CuotaPlan
    description: 'CuotaPlan Report'
    name: 'Email CuotaPlan Report Monthly'
    disabled: true
    triggers:
      - timed: 6 7 20 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh NewProdSales
    description: 'NewProdSales Report'
    name: 'Email NewProdSales Report Monthly'
    disabled: true
    triggers:
      - timed: 15 7 1 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh ContractorPay
    description: 'ContractorPay Report'
    name: 'Email ContractorPay Report Monthly'
    disabled: true
    triggers:
      - timed: 5 7 3 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh ServProf
    description: 'ServProf Report'
    name: 'Email ServProf Report Monthly'
    disabled: true
    triggers:
      - timed: 5 7 3 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh VendorPurchasing
    description: 'Vendor Purchasing Report'
    name: 'Email Vendor Purchasing Report Monthly'
    disabled: true
    triggers:
      - timed: 5 7 5 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh SalesClose
    description: 'Sales Close Report'
    name: 'Email Sales Close Report Monthly'
    disabled: true
    triggers:
      - timed: 0 7 1 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh SalesRepClose
    description: 'Sales Rep Close Report'
    name: 'Email Sales Rep Close Report Monthly'
    disabled: true
    triggers:
      - timed: 10 7 1 * *
- job:
    builders:
      - shell: /home/admin/reports/emailreport.sh DSI
    description: 'DSI Report'
    name: 'Email DSI Report Monthly'
    disabled: true
    triggers:
      - timed: 5 6 1 * *
- job:
    name: 'Email SalesProdCatDetail Report Monthly'
    description: 'SalesProdCatDetail Report'
    disabled: true
    triggers:
      - timed: 7 15 1 * *
    builders:
      - shell: /home/admin/reports/emailreport.sh SalesProdCatDetail
